services:
  cli-proxy-api-canary:
    # Local image ID: sha256:ed6c0d326e0750d22697d9ea0b9cd86c1c1e967477dbb5f09d92f9c8e4769e8c
    image: cliproxyapi-local:v7.2.94-multiorg1
    pull_policy: never
    container_name: CLIProxyAPI-Canary
    restart: unless-stopped
    ports:
      - "192.168.1.114:18319:8317"
    volumes:
      - "./config.yaml:/CLIProxyAPI/config.yaml"
      - "./auths:/root/.cli-proxy-api"
      - "./logs:/CLIProxyAPI/logs"
      - "./plugins:/CLIProxyAPI/plugins"
